# ----------------------------------------------
# BSCH-CSP/Dub/PT: Cloud Services and Platforms
# Student: Alex Meade Wilson (2950871)
# Programming Assignment: Dropbox using GAE
# ----------------------------------------------
runtime: python39
handlers:
  - url : /static
    static_dir : static

  - url : /.*
    script : auto

